export const THEMES = {
  Dark: {
    bg: "#111111",
    textPrimary: "#FFD21F",
    textSecondary: "#D4D4D4",
    textBody: "#EDEDED",
    textHint: "#9A9A9A",
    textStacked: "#CFCFCF",
    hover: "#FF5A3C",
    accent: "#FFD21F",
    accentText: "#111111",
  },
  Light: {
    bg: "#FFFFFF",
    textPrimary: "#111111",
    textSecondary: "#4A4A4A",
    textBody: "#222222",
    textHint: "#6B6B6B",
    textStacked: "#3A3A3A",
    hover: "#D7261E",
    accent: "#FFD21F",
    accentText: "#111111",
  },
} as const;

export type Palette = (typeof THEMES)[keyof typeof THEMES];

// Rooted, not relative: troika resolves these against the document, and a case
// study rewrites the URL to /projects/<slug> while the scene stays up.
export const FONTS = {
  karlaLight: "/fonts/Karla-Light.ttf",
  karlaExtraBold: "/fonts/Karla-ExtraBold.ttf",
} as const;

const SCROLL_TIMELINE_VIEWPORTS = 1.5;

export const CONFIG = {
  heroAssembly: {
    UNFOLD_START: 0.025,
    UNFOLD_END: 0.65,
    SCATTER_START: 0.035,
    SCATTER_END: 0.36,
    REBUILD_START: 0.4,
    REBUILD_END: 0.62,
    FADE_START: 0.68,
    FADE_END: 0.88,
    SPIN_TURNS: 1.8,
    ORBIT_ACCEL_START: 0.18,
    ORBIT_ACCEL_TURNS: 2.4,
    ORBIT_EXPAND_START: 0.12,
    ORBIT_EXPAND_END: 0.62,
    ORBIT_GAP_FILL: 0.72,
    ORBIT_MAX_SCALE: 3,
    ORBIT_FADE_START: 0.82,
    ORBIT_FADE_END: 0.9,
    EXIT_SCALE: 0.88,
    UP_TRAVEL: 0.08,
    MODEL_GAP_PADDING_PX: 16,
    MODEL_GAP_FILL: 0.9,
    EXIT_RISE_START: 0.55,
    EXIT_RISE: 0.14,
    SCATTER_DISTANCE: 0.85,
    SCATTER_SWIRL: 0.35,
    SCATTER_SWIRL_NOISE: 0.2,
    EDGE_FADE_START: 0.82,
  },
  projectOrbitCollision: {
    SIDE_INSET: 0.035,
    HALF_THICKNESS: 0.006,
    SKIN: 0.001,
    NORMAL_EPSILON: 0.0002,
    RESTITUTION: 0.24,
    BOUNCE_START: 0.25,
    BOUNCE_FULL: 2.5,
    FRICTION: 5,
    STEER_RANGE: 0.06,
    STEER_ACCELERATION: 9,
    CONTACTS: 3,
    SWEEP_STEPS: 24,
    SWEEP_SAFETY: 0.8,
  },
  projectOrbit: {
    COUNT: 10,
    RADIUS_MULT: 1.4,
    OFFSET_Y: 0,
    TILT_X: Math.PI / 15,
    TILT_Z: Math.PI / 10,
    GAP: 0.42,
    SEGMENTS: 48,
    SPEED: -0.11,
    IDLE_MAX_FRAME_DELTA: 0.1,
    DIRECTION_EPSILON: 0.0000001,
    DRAG: {
      MIN_PIXELS_PER_RADIAN: 80,
      VELOCITY_WINDOW_MS: 90,
      RELEASE_TIMEOUT_MS: 120,
      MAX_SPEED: 8,
      FLING_THRESHOLD: 0.4,
      FRICTION: 1.6,
      IDLE_RESPONSE: 6,
    },
    CORNER_RADIUS: 0.045,
    BORDER_WIDTH: 0.008,
    FAR_BRIGHTNESS: 0.18,
    GLITCH_TIME_OFFSET: 1.731,
    HOLOGRAM_TINT: 0.16,
    HUD: {
      TEXTURE_WIDTH: 512,
      ATLAS_COLUMNS: 4,
      ATLAS_ROWS: 6,
      CORNER_CUT: 0.1,
      MEDIA_SCALE: 0.76,
      PRIMARY: "#ff405c",
      SECONDARY: "#78e6df",
      PRIMARY_LINEAR: [1.0, 0.05, 0.11],
      SECONDARY_LINEAR: [0.19, 0.79, 0.74],
      PANEL_OPACITY: 0.12,
      VIDEO_BRIGHTNESS: 0.8,
      GLOW_SCALE: 0.4,
    },
    HOLOGRAM_GRAZING_START: 0.04,
    HOLOGRAM_GRAZING_END: 0.24,
    HOLOGRAM_GLOW_WIDTH: 0.045,
    HOLOGRAM_BLEED: 0.22,
    HOLOGRAM_GLOW_FADE_START: 0.12,
    HOLOGRAM_GLOW_FADE_END: 0.2,
    LIGHT_REACH: 0.65,
    OCCLUSION_REACH: 0.45,
    LIGHT_COLOR_TOP: [0.38, 0.9, 1.0],
    LIGHT_COLOR_BOTTOM: [0.8, 0.65, 1.0],
    HOLOGRAM_FADE_START: 0.55,
    HOLOGRAM_DEPTH_FADE: 0.2,
    HOLOGRAM_SCAN_LINES: 72,
    HOLOGRAM_SCAN_STRENGTH: 0.035,
    HOLOGRAM_SCAN_SPEED: 0.06,
    ENTRANCE_START: 0.1,
    ENTRANCE_DURATION: 1.35,
    ENTRANCE_CRUISE_DURATION: 0.45,
    ENTRANCE_TURNS: 1.15,
    ENTRANCE_ORIGIN: Math.PI,
    EXIT_END: 0.55,
    RESPONSE: 4,
    ENTRANCE_RESPONSE: 14,
  },
  monitor: {
    PRESS_DEPTH: 0.0015,
    ACTIVE_EMISSION: 0.18,
    KNOB_ANGLE: Math.PI * 0.75,
    DRAG_PIXELS: 180,
    RESPONSE: 32,
    POWER_OFF_SECONDS: 0.35,
    POWER_ON_SECONDS: 0.48,
    UNDERSCAN_SCALE: 0.97,
    BIAS_RANGE: 0.15,
    GAIN_RANGE: 0.5,
    DOUBLE_TAP_MS: 300,
    TAP_SLOP: 8,
    APERTURE_STRENGTH: 0.45,
    COMPONENT_BLEED: 0.06,
    PHASE_RANGE: 0.45,
    CHROMA_RANGE: 0.95,
    CONTRAST_RANGE: 0.8,
    BRIGHTNESS_LIFT: 0.25,
    BRIGHTNESS_DIM: 0.95,
    NO_SIGNAL_FLOOR: 0.012,
    NO_SIGNAL_NOISE: 0.055,
    NO_SIGNAL_HZ: 24,
    SYNC_ROLL_SPEED: 0.12,
    SYNC_DRIFT: 0.004,
    SYNC_JUMP: 0.008,
    HV_HORIZONTAL_SHIFT: -0.12,
    HV_HORIZONTAL_BLANK: 0.08,
    HV_VERTICAL_BLANK: 0.055,
    PLAYSTATION_SOURCE_ASPECT: 3 / 2,
    PLAYSTATION_CLIPS: [
      "/media/workstation/ps1-generations/generation-01.mp4",
      "/media/workstation/ps1-generations/generation-02.mp4",
      "/media/workstation/ps1-generations/generation-03.mp4",
      "/media/workstation/ps1-generations/generation-04.mp4",
      "/media/workstation/ps1-generations/generation-05.mp4",
      "/media/workstation/ps1-generations/generation-06.mp4",
      "/media/workstation/ps1-generations/generation-07.mp4",
      "/media/workstation/ps1-generations/generation-08.mp4",
      "/media/workstation/ps1-generations/generation-09.mp4",
      "/media/workstation/ps1-generations/generation-10.mp4",
      "/media/workstation/ps1-generations/generation-11.mp4",
    ],
  },
  responsiveScene: {
    MIN_WIDE_CONTENT_WIDTH: 760,
    COMPACT_HEIGHT: 520,
    COMPACT_ASPECT: 0.62,
  },
  antialiasing: {
    MSAA_SAMPLES: 2,
    WORKSTATION_MSAA_SAMPLES: 4,
    SMAA_PRESET: "HIGH",
  },
  performanceMonitor: {
    LOWER_FPS: 50,
    UPPER_FPS: 58,
    DECLINE_COOLDOWN_MS: 3000,
    INCLINE_COOLDOWN_MS: 12000,
    LOW_DPR: 1,
    BALANCED_DPR: 1,
    HIGH_DPR: 1.5,
  },
  scene: {
    CAMERA_FOV: 75,
    CAMERA_REST_Z: 5,
    DETAILS_GROUP_Z: -0.05,
  },
  scrollTimeline: {
    VIEWPORTS: SCROLL_TIMELINE_VIEWPORTS,
    LENIS_DECAY: 6,
    LENIS_DURATION: 1.8,
    LENIS_SETTLE_START: 1.3,
  },
  pointerCamera: {
    ENABLED: true,
    SENSITIVITY: 0.11,
    HORIZONTAL_STRENGTH: 0.18,
    VERTICAL_STRENGTH: 0.06,
    FOCUS_DEPTH: 0.5,
    REFERENCE_FOV: 26.5,
    REFERENCE_ASPECT: 1920 / 968,
    POINTER_CLAMP: 1,
    DEADZONE: 0,
    SMOOTH_TIME: 1,
    RETURN_DURATION: 3,
    REENTRY_DURATION: 1.5,
    REENTRY_SPEED: 0.5,
    REVEAL_START: 0.7,
    REVEAL_FULL: 0.95,
    SCROLL_ATTENUATION: 0.6,
    SCROLL_FULL_SPEED: 2,
    SETTLE_EPSILON: 0.00001,
  },
  workstation: {
    CRT_MODEL_URL: "/glbs/crt-monitor.glb?v=bvm-8044qd-closed-badge",
    KEYBOARD_MODEL_URL: "/glbs/keyboard.glb",
    ENERGY_CAN_MODEL_URL: "/glbs/monster-mango-loco.glb",
    ENERGY_CAN_YAW: -0.12 - Math.PI / 9,
    TURNTABLE_MODEL_URL: "/glbs/turntable.glb",
    TURNTABLE_POSITION: { x: 0.17, y: 0, z: 0.025 },
    TURNTABLE_ROTATION: { x: 0, y: -3, z: 0 },
    TURNTABLE_SCALE: 1,
    DESK_MODEL_URL: "/glbs/workstation-desk.glb",
    KEYBOARD_POSITION: { x: 0.055, y: 0, z: 0.02 },
    KEYBOARD_ROTATION: { x: 0, y: -2, z: 0 },
    KEYBOARD_SCALE: 1,
    DESK_POSITION: { x: 0.3, y: 0, z: -0.29 },
    DESK_SCALE: { x: 2, y: 1.6, z: 0.91 },
    MONITOR_POSITION: { x: 0.055, y: 0, z: -0.225 },
    MONITOR_YAW: -6,
    CABINET_POSITION: { x: -1.101, y: 0.225, z: -0.35 },
    CABINET_SIZE: { x: 0.882, y: 0.945, z: 0.53 },
    CABINET_MODEL_URL: "/glbs/music-cabinet.glb",
    RECORD_COVER_URL: "/textures/music-cabinet/the-prodigy-one-love.webp",
    CABINET_PANEL: 0.024,
    CABINET_PLINTH: 0.063,
    MOUSE_POSITION: { x: 0.3, y: 0, z: 0.02 },
    CONTROLLER_POSITION: { x: -0.32, y: 0, z: -0.04 },
    CONTROLLER_MODEL_URL: "/glbs/controller.glb",
    CONTROLLER_WIDTH: 0.16,
    CONTROLLER_YAW: 197,
    CONTROLLER_ENV_INTENSITY: { day: 0.4, night: 0.12 },
    LAMP_SCALE: 0.78,
    LAMP_POSITION: { x: -0.34, y: 0, z: -0.23 },
    LEVITATING_LAMP: {
      WOOD_URL: "/textures/music-cabinet/walnut.jpg",
      BASE_RADIUS: 0.105,
      BASE_HEIGHT: 0.03,
      BASE_BEVEL: 0.008,
      BULB_HEIGHT: 0.085,
      LIGHT_HEIGHT: 0.137,
      GLASS_PROFILE: [[0.023, 0.035], [0.025, 0.044], [0.025, 0.071], [0.029, 0.093], [0.043, 0.115], [0.059, 0.141], [0.065, 0.164], [0.06, 0.191], [0.044, 0.211], [0.022, 0.223], [0, 0.226]],
      FLOAT_AMPLITUDE: 0.004,
      FLOAT_PERIOD: 5.5,
      ROTATION_PERIOD: 70,
      INITIAL_YAW: 0.35,
      SWITCH_DAMPING: 18,
      INTERACTION_REVEAL: 0.85,
      FILAMENT_COLOR: "#ffb34d",
      FILAMENT_COLD_COLOR: "#493321",
      FILAMENT_INTENSITY: 7,
      FILAMENT_RADIUS: 0.0007,
      FILAMENT_COIL_RADIUS: 0.0016,
      FILAMENT_TURNS: 42,
      FILAMENT_POINTS: [[-0.023, 0.097, 0.009], [-0.008, 0.185, 0], [0.008, 0.185, 0], [0.023, 0.097, 0.009]],
      LIGHT_DISTANCE: 1.2,
      GLASS: { color: "#ffe5c4", transmission: 1, thickness: 0.008, roughness: 0.075, ior: 1.15, clearcoat: 1, envMapIntensity: 0.7 },
    },
    WINDOW_POSITION: { x: -0.96, y: 0.8, z: -0.69 },
    WINDOW_SIZE: { x: 0.86, y: 0.95, z: 0.08 },
    ARTWORK_PORTRAIT_URL: "/media/workstation/artwork-portrait.webp",
    ARTWORK_RONALDO_URL: "/media/workstation/artwork-ronaldo.webp",
    ARTWORK_PORTRAIT_POSITION: { x: 0.77, y: 0.72, z: -0.692 },
    ARTWORK_RONALDO_POSITION: { x: 1.08, y: 0.7365, z: -0.692 },
    ARTWORK_PORTRAIT_SIZE: { x: 0.3, y: 0.42 },
    ARTWORK_RONALDO_SIZE: { x: 0.28, y: 0.387 },
    ARTWORK_ROTATION: { portrait: 0, ronaldo: 0 },
    SKATEBOARD_POSITION: { x: 0.17, y: 0.69, z: -0.59 },
    PLANT_POSITION: { x: -1.22, y: 0.34, z: -0.61 },
    CAMERA_END: { x: -0.02, y: 0.53, z: 0.72 },
    CAMERA_TARGET: { x: -0.02, y: 0.27, z: -0.14 },
    SKATEBOARD_SIZE: { width: 0.2032, length: 0.805, thickness: 0.008 },
    SKATEBOARD_MODEL_URL: "/glbs/skateboard-deck.glb",
    SKATEBOARD_ENVIRONMENT_URL: "/hdri/city.hdr",
    SKATEBOARD_ENV_INTENSITY: { day: 0.85, night: 0.75 },
    POLAROIDS_POSITION: { x: -0.43, y: 0.63, z: -0.615 },
    ENERGY_CAN_POSITION: { x: 0.50, y: 0, z: -0.20 },
    LEFT_SPEAKER_POSITION: { x: -0.47, y: 0, z: -0.59 },
    RIGHT_SPEAKER_POSITION: { x: 0.51, y: 0, z: -0.56 },
    SPEAKER_SIZE: { x: 0.145, y: 0.23, z: 0.17 },
    SPEAKER_MODEL_URL: "/glbs/edifier-r1280dbs.glb",
    SPEAKER_ENV_INTENSITY: { day: 0.4, night: 0.12 },
    SPEAKER_YAW: 12,
    FEATURED_RECORD_POSITION: { x: -0.625407508, y: 0, z: -0.255 },
    FEATURED_RECORD_YAW: 90,
    FEATURED_RECORD_LEAN: 8,
    RECORD_THICKNESS: 0.006,
    RECORD_SIZE: 0.315,
    SILL_BOOKS_POSITION: { x: -0.76, y: 0.34, z: -0.6 },
    CAMERA_CURVE: { x: 0.035, y: 0.05, z: 0.1 },
    CAMERA_ARC_START: 0.18,
    CAMERA_MAX_ZOOM_OUT: 0.56,
    CAMERA_NARROW_WIDTH: 0.72,
    PROXY_YAW: { mouse: -5, skateboard: -90 },
    LIGHT_WINDOW_OFFSET_Z: 0.6,
    LIGHT_LAMP_POWER_MULT: 0.45,
    LIGHT_NIGHT_FILL_MULT: 0.3,
    LIGHT_NIGHT_WINDOW_MULT: 0.08,
    LIGHT_DAY_LAMP_MULT: 0.025,
    LIGHTING_MODE: "night" as "day" | "night",
    WINDOW_LIGHT: 1.4,
    LAMP_LIGHT: 2.8,
    FILL_LIGHT: 0.35,
    WALL_SIZE: { x: 10, y: 4, z: 0.12 },
    RIGHT_WALL_X: 1.25,
    RIGHT_WALL_DEPTH: 3,
    RIGHT_WALL_COLOR: "#96998c",
    WALL_CENTER_Y: 0.8,
    WALL_COLOR: "#35383d",
    WALL_ROUGHNESS: 0.92,
    WORKSTATION_CAMERA_Y: -0.075,
    CONTACT_SHADOW_OPACITY: 0.72,
    CONTACT_SHADOW_BLUR: 2.5,
    CONTACT_SHADOW_RESOLUTION: 512,
    CONTACT_SHADOW_FAR: 0.6,
    CONTACT_SHADOW_OFFSET: 0.0002,
    CONTACT_SHADOW_REVEAL: 0.45,
    CRT_SCREEN_CLEARANCE: 0.0005,
    CRT_SCREEN_RINGS: 48,
    CRT_CONTOUR_STEP: 0.008,
    CRT_INNER_BORDER_WIDTH: 0.009,
    CRT_BORDER_SEGMENTS: 8,
    CRT_MORPH_END: 0.45,
    CRT_BARREL: 0.012,
    CRT_BORDER: 0.003,
    CRT_ACTIVE_EDGE_BOW: 0.012,
    CRT_EDGE_SOFTNESS: 0.004,
    CRT_VIGNETTE: 0.16,
    CRT_SCANLINES: 480,
    CRT_SCANLINE_STRENGTH: 0.045,
    CRT_PHOSPHOR_STRENGTH: 0.018,
    CRT_CHROMATIC: 0.00035,
    CRT_NOISE: 0.0015,
    CRT_GLOW: 0.055,
    CRT_REFLECTION: 0.035,
    CRT_TARGET_MAX_SIZE: 2048,
    CRT_TARGET_BALANCED_MAX_SIZE: 1536,
    CRT_TARGET_LOW_MAX_SIZE: 1024,
    CRT_TARGET_MIN_SIZE: 384,
    CRT_TARGET_PROJECTED_SCALE: 1.25,
    TARGET_RESIZE_THRESHOLD: 0.25,
    PAGE_TARGET_HIGH_MAX_SIZE: 2048,
    PAGE_TARGET_BALANCED_MAX_SIZE: 1536,
    PAGE_TARGET_LOW_MAX_SIZE: 1024,
    REVEAL_VIEWPORTS: 1.75,
    PLANE_ASPECT: 4 / 3,
    PLANE_SEGMENTS_X: 32,
    PLANE_SEGMENTS_Y: 24,
    PLANE_Z: -0.18,
    BROWSER_CHROME_HEIGHT_MULT: 0.075,
    BROWSER_REVEAL_START: 0.01,
    REVEAL_CAMERA_FILL: 0.3,
    BROWSER_SAFE_MARGIN_MULT: 0.045,
    DOCK_HEIGHT_MULT: 0.11,
    DOCK_ITEM_GAP_MULT: 0.11,
    DOCK_MAGNIFICATION_RADIUS_MULT: 3,
    DOCK_MAGNIFICATION_MAX: 1.5,
    DOCK_MAGNIFICATION_TOTAL_MULT: 2,
    DOCK_MAGNIFICATION_RESPONSE: 18,
    DOCK_RUNNING_DOT_RADIUS_MULT: 0.023,
    DOCK_RUNNING_DOT_BOTTOM_MULT: 0.055,
    DOCK_SCALE: 0.6,
    DOCK_OFFSET_X: 0,
    DOCK_OFFSET_Y: 0.025,
    SAFARI_CHROME_SCALE: 0.8,
    SAFARI_CONTROLS_SCALE: 0.88,
    SAFARI_ADDRESS_SCALE: 1.2,
    SAFARI_BOTTOM_SAFE_AREA: 0.012,
    TEXTURE_MAX_DIMENSION: 2048,
    BROWSER_CONTROL_RADIUS_MULT: 0.18,
    BROWSER_SIDE_PADDING_MULT: 0.42,
    BROWSER_CONTROL_GAP_MULT: 0.3,
    BROWSER_ADDRESS_WIDTH_MULT: 0.46,
    BROWSER_ADDRESS_HEIGHT_MULT: 0.42,
    BROWSER_ADDRESS_FONT_MULT: 0.25,
    BROWSER_BAR_COLOR: "#c8cbcc",
    BROWSER_ADDRESS_COLOR: "#b7bbbd",
    BROWSER_ICON_COLOR: "#5f6364",
    BROWSER_LIGHTS: ["#ff5f57", "#febc2e"] as const,
    GENIE_DURATION: 0.68,
    GENIE_MIN_DURATION: 0.08,
    GENIE_RESTORE_DURATION: 0.56,
    GENIE_REDUCED_DURATION: 0.16,
    GENIE_ROW_STAGGER: 0.78,
    GENIE_TARGET_SCALE_MULT: 0.72,
    RETURN_BRIDGE_REVEAL_BREAKPOINT: 0.32,
    RETURN_BRIDGE_APP_SCROLL_SPAN: 0.48,
    RETURN_BRIDGE_AUTO_SCROLL_DELAY: 0.18,
    RETURN_BRIDGE_AUTO_SCROLL_MIN_SPEED: 260,
    RETURN_BRIDGE_AUTO_SCROLL_DURATION: 1.04,
    RETURN_BRIDGE_AUTO_SCROLL_REDUCED_DURATION: 0.16,
    VSCODE_SCROLLBAR_THICKNESS_MULT: 0.055,
    VSCODE_SCROLLBAR_HIT_MULT: 0.55,
    VSCODE_SCROLLBAR_MIN_THUMB_MULT: 0.42,
    VSCODE_SCROLLBAR_IDLE_ALPHA: 0.38,
    VSCODE_SCROLLBAR_HOVER_ALPHA: 0.68,
    VSCODE_SCROLLBAR_ACTIVE_ALPHA: 0.88,
    VSCODE_SOURCE_REFRESH_MS: 1000,
  },
  loader: {
    REVEAL_DURATION: 0.5,
    ODOMETER_DURATION: 2,
    ODOMETER_DURATION_REPEAT: 0.5,
  },
  model: {
    PIKACHU_ROTATION: { x: 0.08, y: -0.38, z: 0 },
    FUR: {
      SHELLS: 24,
      SHELLS_LOW: 10,
      LENGTH: 0.085,
      GRAVITY: 0.03,
      DENSITY: 150,
      CLUMP: 1.6,
      ROOT_SHADE: 0.5,
      TIP_LIGHT: 1.15,
      ROUGHNESS: 0.85,
      ENV_INTENSITY: 0.6,
    },
    TRANSMISSION_MIN_SCALE: 0.02,
    PARTICLE_MIN_INTERACTION_SCALE: 0.001,
    TRANSMISSION_RESOLUTION: 256,
    TRANSMISSION_RESOLUTION_MOBILE: 128,
    TRANSMISSION_SAMPLES: 4,
    TRANSMISSION_SAMPLES_MOBILE: 2,
    GLASS: {
      thickness: 0.65,
      roughness: 0.2,
      transmission: 0.97,
      ior: 0.9,
      chromaticAberration: 1,
      backside: false,
    },
    FRAGMENTS: {
      CELLS: 18,
      CELLS_LOW: 13,
      GAP: 0.025,
      DEPTH_RATIO: 0.28,
      SPIN: 1.2,
      SEAM_CLOSED_DISTANCE: 0.02,
      SEAM_OPEN_DISTANCE: 0.3,
      INTERIOR_REVEAL: 0.02,
      ENTRANCE_MOMENTUM: 9,
      ENTRANCE_DURATION: 1.2,
      ENTRANCE_EASE: "power3.out",
      ENTRANCE_MAX_SCALE_SPEED: 8,
      ENTRANCE_MAX_FRAME_DELTA: 0.1,
    },
    PARTICLE_COUNT: 16384,
    PARTICLE_COUNT_LOW: 4096,
    PARTICLE_COUNT_MIN: 256,
    PARTICLE_COUNT_MAX: 65536,
    PARTICLE_SIZE_MIN: 0.1,
    PARTICLE_SIZE_MAX: 6,
    PARTICLE_RADIUS: 0.007,
    PARTICLE_RADIUS_LOW: 0.011,
    PARTICLE_CURSOR_RADIUS: 0.5,
    PARTICLE_CURSOR_STRENGTH: 24,
    PARTICLE_REPULSION: 5,
    PARTICLE_RETURN_STRENGTH: 32,
    PARTICLE_DAMPING: 7,
    PARTICLE_MAX_CURSOR_SPEED: 12,
    PARTICLE_HEAT_GAIN: 0.16,
    PARTICLE_HEAT_DECAY: 2.5,
    PARTICLE_TIME_STEP: 1 / 120,
    PARTICLE_MAX_DELTA: 1 / 30,
    PARTICLE_COLOR: "#b2b9c4",
    PARTICLE_HOT_COLOR: "#ff7744",
    BASE_MODEL_Y: 0.1,
    INTERACTION_LOCK_EPSILON: 0.07,
    MODEL_UP_TRAVEL_FACTOR: 0.25,
    SCALE_OUT_START: 0.2,
    SCALE_OUT_END: 0.9,
    NARROW_TRANSITION_START: 0.18,
    NARROW_HERO_SCALE: 1.22,
    NARROW_COMPACT_HERO_SCALE: 0.96,
    NARROW_COMPACT_X_FRACTION: 0.22,
    RETURN_TO_CENTER_SMOOTHNESS: 8,
    RETURN_VELOCITY_DAMPING: 10,
    RETURN_SNAP_EPSILON: 0.0025,
    DETAILS_POPUP_START: 0.9,
    DETAILS_POPUP_SCALE: 0.6,
    COMPANION: {
      WIDE: { X: 0.37, Y: -0.3, SCALE: 1 },
      NARROW: { X: 0.33, Y: -0.38, SCALE: 0.7 },
    },
    FOLD_FADE_CLEARANCE_MULT: 0.03,
    FOLD_FADE_SPAN_MULT: 0.14,
    POPUP_RAMP_SPAN: 0.1,
    IDLE_MAX_ANGLE: Math.PI / 36,
    CURSOR_MAX_ANGLE: Math.PI / 18,
    TILT_RESPONSE: 4,
    IDLE_ROTATION_SPEED: 0.45,
    DEPTH_Z: 2,
  },
  detailsLayout: {
    HEADING_SIZE_MULT: 0.03,
    HEADING_MIN_PX: 26,
    HEADING_MAX_PX: 72,
    BODY_SIZE_MULT: 0.5,
    SECTION_TRAVEL_MULT: 1.16,
    TARGET_BASE_Y_MULT: -0.25,
    SECTION_TOP_OFF_MULT: 0.35,
    SECTION_GAP_MULT: 2.4,
    RIGHT_TITLE_OFFSET_MULT: 0.2,
    GAP_MULT: 0.08,
    BODY_TOP_OFFSET_MULT: 0.38,
    HEADING_LINE_HEIGHT_MULT: 1.1,
    BODY_LINE_HEIGHT_MULT: 1.5,
    PROJECT_ROW_PITCH_MULT: 2.25,
    LETTER_SPACING: -0.03,
    // Pixels the sheet has to travel before the pointer intersection is
    // re-run, so hover follows the content under a stationary cursor.
    POINTER_SYNC_PX: 0.5,
    REVEAL_MARGIN_MULT: 0.04,
    BIO_IMAGE_WIDTH_MULT: 0.26,
    BIO_IMAGE_ASPECT: 2000 / 1500,
    BIO_CONTENT_TOP_MULT: 1.75,
    BIO_COLUMN_GAP_MULT: 0.04,
    BIO_REVEAL_LINES: 9,
    BIO_REVEAL_BLOCK_Z: 0.02,
    BIO_REVEAL_BLOCK_OVERHANG: 1.1,
    BIO_REVEAL_BLOCK_RADIUS_PX: 8,
    NARROW_HEADING_SIZE_MULT: 0.09,
    NARROW_HEADING_MIN_PX: 28,
    NARROW_HEADING_MAX_PX: 42,
    NARROW_BODY_SIZE_MULT: 0.56,
    NARROW_BODY_MIN_PX: 16,
    NARROW_BODY_MAX_PX: 20,
    NARROW_BODY_LINE_HEIGHT_MULT: 1.5,
    NARROW_BODY_GAP_MULT: 0.8,
    NARROW_SECTION_GAP_MULT: 1.9,
    NARROW_SKILLS_COLUMN_GAP_MULT: 0.04,
    NARROW_MODEL_INTERLUDE_MULT: 0.33,
    NARROW_MODEL_INTERLUDE_COMPACT_MULT: 0.24,
    NARROW_MODEL_INTERLUDE_MIN_PX: 104,
    NARROW_MODEL_INTERLUDE_MAX_PX: 280,
    NARROW_BIO_IMAGE_WIDTH_MULT: 0.7,
    NARROW_BIO_IMAGE_GAP_MULT: 0.85,
  },
  detailsReveal: {
    BLOCK_WIDTH_MULT: 1.01,
    BLOCK_HEIGHT_MULT: 1.1,
    BLOCK_RADIUS_PX: 8,
    BLOCK_SEGMENTS: 6,
    BLOCK_Z: 0.002,
    BUTTON_Z: -0.002,
    BUTTON_SEGMENTS: 24,
  },
  detailsCurl: {
    FOLD_OFFSET_MULT: 0,
    BOTTOM_OFFSET_MULT: 0,
    RADIUS_MULT: 0.085,
    MAX_ANGLE: 1.5,
    FADE_ANGLE_START: 0.15,
    FADE_ANGLE_END: 1.25,
    EDGE_FADE_TOP_MULT: 0.85,
    EDGE_FADE_BOTTOM_MULT: 0.14,
    EDGE_FADE_CUT_MULT: 0.25,
    EDGE_FADE_RENDER_ORDER: 20,
    ABOVE_EDGE_FADE_RENDER_ORDER: 30,
    GLYPH_DETAIL: 3,
    ARROW_SEGMENTS: 4,
    IMAGE_SEGMENTS: 24,
  },
  projectPreview: {
    // The screenshots are 1600x1000.
    ASPECT: 1.6,
    // Plate width as a fraction of the viewport's.
    WIDTH_FRACTION: 0.28,
    MOBILE_WIDTH_FRACTION: 0.84,
    MOBILE_COMPACT_WIDTH_FRACTION: 0.72,
    MOBILE_ACTIVATION_VIEWPORT_Y: 0.38,
    MOBILE_CENTER_VIEWPORT_Y: 0.7,
    MOBILE_COMPACT_CENTER_VIEWPORT_Y: 0.68,
    CORNER_RADIUS_MULT: 0.05,
    // Crossing a row boundary fires leave before enter. Waiting this long
    // before dropping the hover keeps the list one continuous region, so
    // sweeping down it swaps the screenshot instead of replaying the
    // entrance.
    HOVER_GRACE_MS: 90,
    // Damping the plate chases the pointer with. High enough that it reads
    // as sitting on the cursor; the lag it does keep is what the bend is
    // measured from.
    FOLLOW_SMOOTHING: 22,
    // Grid the two-axis trailing-centre bend is sampled over.
    BEND_SEGMENTS_X: 32,
    // Also what the fold is rolled over, so the plate needs rows the way
    // the details sheet does.
    BEND_SEGMENTS_Y: 28,
    // Peak lag of the plate's centre, as a fraction of its own span.
    BEND_MULT: 0.275,
    // Peak per-channel UV split, in texture units.
    ABERRATION_MULT: 0.06,
    // Pointer speed (in normalised units per second) that saturates both.
    VELOCITY_FULL_SCALE: 2.6,
    VELOCITY_SMOOTHING: 11,
    // Horizontal bands the glitch slices the plate into, and reveals it in.
    GLITCH_BANDS: 18,
    // Peak horizontal slice offset, in texture units.
    GLITCH_SLICE: 0.07,
    // Spare plate past each edge, as a fraction of the plate's own span. A
    // sliced band carries the plate's edge with it and the channel split
    // carries it further, and this is the room they have to land outside
    // the frame in. Wider than tall: only the slice travels sideways.
    GLITCH_BLEED: [0.22, 0.09] as [number, number],
    // How far into that room a torn band stays solid before it dissolves,
    // so nothing is ever cut square at the mesh's own edge.
    GLITCH_BLEED_SOLID: 0.25,
    // Peak channel split the glitch adds on top of the travel's own.
    GLITCH_SPLIT: 0.018,
    // Times a second the slice pattern reshuffles.
    GLITCH_HZ: 12,
    ENTER_REVEAL_DURATION: 0.26,
    ENTER_GLITCH_DURATION: 0.42,
    ENTER_SCALE_FROM: 0.94,
    ENTER_SCALE_DURATION: 0.3,
    EXIT_REVEAL_DURATION: 0.16,
    EXIT_GLITCH_DURATION: 0.12,
    EXIT_SCALE_TO: 0.97,
    SWAP_GLITCH_DURATION: 0.22,
    // Over the details content, so the plate covers the buttons, but under
    // the edge fade, which is what darkens it at both ends.
    RENDER_ORDER: 15,
    REST_GLITCH: 0.38,
    REST_ABERRATION: 0.012,
    TUNE_SATURATION: [0.3, 1.15] as [number, number],
    TUNE_CONTRAST: [0.82, 1.1] as [number, number],
    TUNE_BRIGHTNESS: [0.82, 1.12] as [number, number],
    CHARGE_SCALE_GAIN: 0.02,
    // The caption is its own mesh, sharing the plate's geometry so it bends
    // and curls identically, but skipping the glitch so it stays readable.
    // Fractions of the plate, which keeps it resolution-independent.
    CAPTION_TEXTURE_WIDTH: 1024,
    CAPTION_FONT_FRACTION: 13 / 360,
    CAPTION_PAD_X_FRACTION: 16 / 360,
    CAPTION_BASELINE_FRACTION: 0.17,
    CAPTION_BAR_FRACTION: 2 / 225,
    CAPTION_BAR_GAP_FRACTION: 6 / 225,
    CAPTION_LEAD: "Click for case study",
    CAPTION_TRAIL: "Hold for live site",
  },
  caseStudy: {
    ACTIVE_EPSILON: 1e-4,
    // Fraction of the landed frame's width the plate spans. Below ~0.8 the
    // frame still reads as a page with margins rather than as a fullscreen
    // image, which is what keeps the copy underneath feeling attached.
    FILL: 0.72,
    // How far above the landed frame's centre the plate settles, in frame
    // heights. Just enough that the gap under it does not look like an
    // accident before the copy arrives in it.
    PLATE_OFFSET: 0.03,
    FLIGHT_DURATION: 0.95,
    // Shorter on the way out: the list is a place the viewer already knows,
    // so returning to it does not have to be shown at the same length.
    CLOSE_DURATION: 0.71,
    // The list is what the camera flies past, so it has to be gone before
    // the frame is small enough to show how magnified it has become.
    LIST_DIM_START: 0.2,
    LIST_DIM_SPAN: 0.35,
    // The model hangs at CONFIG.model.DEPTH_Z, in front of the sheet and so
    // in front of the plate — the camera flies straight through it. It has
    // to leave faster than the list does: its magnification climbs as the
    // camera closes on it, and only a ramp this short outruns that.
    MODEL_EXIT_SPAN: 0.25,
    // The copy only starts once the frame has almost stopped moving; a
    // stagger read against a travelling camera reads as drift.
    COPY_START: 0.72,
    COPY_RAMP: 0.28,
    COPY_REVEAL_SPAN: 0.5,
    COPY_REVEAL_STAGGER: 0.12,
    // Rise per line before it lands, in that line's own em.
    COPY_REVEAL_RISE: 0.6,
    // Body size and measure, as fractions of the landed frame's width.
    EM_MULT: 0.019,
    TEXT_WIDTH_MULT: 0.62,
    // Gap between the plate's bottom edge and the first line, in frame
    // heights.
    COPY_GAP_MULT: 0.085,
    TITLE_SIZE_EM: 2.3,
    TITLE_LINE_HEIGHT: 1.08,
    META_SIZE_EM: 0.78,
    META_LINE_HEIGHT: 1.4,
    // The metadata line is one breath, so it is allowed past the measure
    // the prose is set to rather than wrapping in the middle of a stack.
    META_WIDTH_MULT: 1.4,
    LEDE_SIZE_EM: 1.28,
    LEDE_LINE_HEIGHT: 1.35,
    BODY_LINE_HEIGHT: 1.62,
    GAP_AFTER_TITLE_EM: 0.55,
    GAP_AFTER_META_EM: 1.5,
    GAP_AFTER_LEDE_EM: 1.1,
    GAP_AFTER_PARAGRAPH_EM: 0.9,
    // The name mark doubles as the way out, sat on one line with an Esc
    // hint in the band above the image. In frame heights, leaving room over
    // it before the frame's own top edge.
    MARK_GAP_MULT: 0.055,
    MARK_SIZE_EM: 1,
    // Padding around the mark's twin, in its own em, so the hit area is
    // bigger than the glyphs the way the header's items are.
    MARK_HIT_PAD_EM: 0.75,
    RETURN_HINT: "Esc to close",
    // Troika and the browser disagree slightly on tracking; the details
    // twins carry the same correction so selection and focus sit on top of
    // the glyphs rather than beside them.
    HTML_LETTER_SPACING_OFFSET: -0.004,
    // Wheel travel is read in frame heights so a flick moves the copy the
    // same distance whatever the window is.
    SCROLL_DAMPING: 9,
    KEY_SCROLL_STEP_PX: 40,
    KEY_SCROLL_PAGE_FRACTION: 0.9,
    // Room past the last line, so it does not end flush with the frame's
    // bottom edge.
    SCROLL_OVERSHOOT_MULT: 0.15,
    // Above the edge fade, which is faded out from under the case study
    // rather than drawn over it.
    RENDER_ORDER: 40,
    MOBILE_FILL: 0.9,
    MOBILE_RETURN_TOP_FRACTION: 0.05,
    MOBILE_EM_MULT: 0.045,
    MOBILE_TEXT_WIDTH_MULT: 0.88,
    MOBILE_FLIGHT_DURATION: 0.72,
    MOBILE_CLOSE_DURATION: 0.55,
    MOBILE_CTA_SIZE_EM: 0.84,
    MOBILE_CTA_PAD_X_EM: 0.9,
    MOBILE_CTA_PAD_Y_EM: 0.72,
    MOBILE_CTA_INSET_EM: 0.85,
    MOBILE_SCROLL_Z_INDEX: 16_777_270,
    MOBILE_CONTROL_Z_INDEX: 16_777_271,
  },
  projectGesture: {
    PRESS_SCALE: 0.97,
    PRESS_DURATION: 0.12,
    CHARGE_DELAY: 0.15,
    CHARGE_DURATION: 0.5,
    REWIND_DURATION: 0.18,
  },
  detailsLink: {
    ARROW_SIZE_MULT: 0.4,
    ARROW_GAP_MULT: 0.3,
    ARROW_TWIN_OVERHANG_EM: 0.2,
    ARROW_NUDGE_FACTOR: 0.25,
    ARROW_DURATION: 0.2,
    INTERACT_MIN_OPACITY: 0.05,
    BUTTON_TEXT_FADE_POWER: 0.5,
    BUTTON_PAD_X_EM: 0.8,
    BUTTON_PAD_Y_EM: 0.78,
  },
  detailsTimings: {
    HEADING_DELAY: 0.1,
    BODY_DELAY: 0.18,
    BODY_STAGGER_STEP: 0.07,
    SKILLS_STAGGER_STEP: 0.06,
  },
  header: {
    FONT_SIZE: 0.0105,
    MARGIN_Y_PX: 28,
    HTML_Z_INDEX: 16777271,
    LETTER_SPACING: -0.02,
    HTML_LETTER_SPACING_OFFSET: -0.004,
    SLOT_TS: [0, 0.2, 0.56, 0.75, 1],
    SEGMENT_GAP_EM: 0.45,
    HIT_PAD_EM: 0.6,
    HOVER_DURATION: 0.15,
    REVEAL_DELAY: 0.35,
    REVEAL_STAGGER: 0.07,
    FADE_DURATION: 0.6,
    NARROW_FONT_MIN_PX: 12,
    NARROW_FONT_MAX_PX: 15,
    NARROW_FONT_SIZE_MULT: 0.038,
    NARROW_MARGIN_Y_PX: 24,
    NARROW_THEME_SLOT_T: 0.74,
    NARROW_ICON_SIZE_PX: 16,
  },
  heroText: {
    LABEL_EXIT_START: 0.05,
    LABEL_EXIT_END: 0.1,
  },
  title: {
    TARGET_SCALE: 0.75,
    HINT_SCROLL_HIDE_EPSILON: 0.0005,
    HINT_SCROLL_SHOW_EPSILON: 0.0001,
    STACKED_FADE_START: 0.12,
    VISUAL_FONT_CORRECTION_X: 0.05,
    DELAY_FIRST_RUN: 2.5,
    DELAY_REPEAT: 0.8,
    DURATION_FIRST_RUN: 1.5,
    FADE_DURATION_FIRST_RUN: 1.2,
    FADE_POSITION_FIRST_RUN: 0.8,
  },
  customAberration: {
    COLUMNS: 40.0,
    LERP_FACTOR_MULT: 9.75,
    INTENSITY_LERP_MULT: 3.0,
    INTENSITY_MIN: 0.005,
    SAFE_DELTA_MIN: 0.0001,
    VEL_MULT: 0.016666,
    SCROLL_TAPS: 8,
    SCROLL_TAPS_MIN: 3,
    SCROLL_TAPS_COARSE: 4,
    SCROLL_INTENSITY_COARSE: 0.55,
    // Device pixels the pass can cover at full tap count. Above this the
    // taps are scaled down, since each one costs three dependent fetches
    // over the entire screen.
    SCROLL_TAP_PIXEL_BUDGET: 2_500_000,
    // Ceiling PerformanceMonitor raises DPR to. Budgeting against it keeps
    // the tap count stable while the monitor adapts, so a DPR change never
    // forces a shader recompile.
    SCROLL_TAP_DPR_CEILING: 1.5,
    SCROLL_BLUR: 0.022,
    SCROLL_SPLIT: 0.04,
    SCROLL_VEL_SCALE: 20.0,
    SCROLL_VEL_CLAMP: 1.0,
    SCROLL_ATTACK_MULT: 30.0,
    SCROLL_RELEASE_MULT: 14.0,
    SCROLL_MIN: 0.004,
    SCROLL_VIGNETTE_X_WEIGHT: 0.5,
    SCROLL_VIGNETTE_FLOOR: 0.35,
    SCROLL_VIGNETTE_INNER: 0.15,
    SCROLL_VIGNETTE_OUTER: 0.5,
  },
  heroLayout: {
    TITLE_Y_MULTIPLIER: 0.7,
    HERO_Y_MULTIPLIER: 1.05,
    SUBTITLE_Y_MULTIPLIER: 0.22,
    SUBTITLE_PROGRESS_POWER: 1.05,
    TITLE_FONT_SIZE: 0.127,
    TITLE_FONT_VISUAL_OFFSET: 0.14,
    SUBTITLE_FONT_SIZE: 0.03025,
    PROFESSION_FONT_SIZE: 0.02,
    PROFESSION_PADDING_Y: 8,
    PROFESSION_LINE_THICKNESS: 1,
    PROFESSION_LINE_WIDTH: 0.9,
    PROFESSION_EXIT_DISTANCE: 0.14,
    NARROW_TITLE_FONT_SIZE: 0.105,
    NARROW_TITLE_MIN_PX: 34,
    NARROW_TITLE_MAX_PX: 42,
    NARROW_TITLE_COMPACT_MIN_PX: 32,
    NARROW_TITLE_COMPACT_MAX_PX: 34,
    NARROW_TITLE_LETTER_SPACING: -0.03,
    NARROW_SETTLED_TITLE_MIN_PX: 18,
    NARROW_SETTLED_TITLE_MAX_PX: 22,
    NARROW_SETTLED_TITLE_SCALE: 0.56,
    NARROW_TITLE_TRANSITION_START: 0.04,
    NARROW_TITLE_TRANSITION_END: 0.72,
    NARROW_SUBTITLE_FONT_SIZE: 0.046,
    NARROW_SUBTITLE_MIN_PX: 15,
    NARROW_SUBTITLE_MAX_PX: 18,
    NARROW_SUBTITLE_LINE_HEIGHT: 1.02,
    NARROW_SUBTITLE_TOP_MULT: 0.14,
    NARROW_SUBTITLE_TOP_MIN_PX: 104,
    NARROW_SUBTITLE_TOP_MAX_PX: 124,
    NARROW_SUBTITLE_COMPACT_TOP_PX: 52,
    NARROW_SUBTITLE_EXIT_END: 0.52,
    NARROW_SUBTITLE_EXIT_DISTANCE: 0.24,
    NARROW_TITLE_GAP_PX: 24,
    NARROW_TITLE_COMPACT_GAP_PX: 14,
    NARROW_STICKY_TITLE_TOP_PX: 68,
    NARROW_STICKY_TITLE_COMPACT_TOP_PX: 54,
    NARROW_ROLE_FONT_SIZE: 0.042,
    NARROW_ROLE_FONT_MIN_PX: 14,
    NARROW_ROLE_FONT_MAX_PX: 16,
    NARROW_ROLE_SETTLED_PX: 14,
    NARROW_ROLE_ROW_PITCH_PX: 30,
    NARROW_ROLE_INDEX_OFFSET_PX: 42,
    NARROW_ROLE_INDEX_SCALE: 0.72,
    NARROW_ROLE_INDEX_TRACKING: 0.08,
    NARROW_ROLE_BOTTOM_PX: 46,
    NARROW_ROLE_COMPACT_BOTTOM_PX: 32,
    NARROW_ROLE_COMPACT_INSET_PX: 42,
    NARROW_ROLE_STICKY_GAP_PX: 12,
    NARROW_ROLE_REVEAL_STAGGER: 0.06,
    NARROW_ROLE_RULE_REVEAL_DURATION: 0.45,
    NARROW_PROFESSION_FONT_SIZE: 0.05,
    NARROW_PROFESSION_MIN_PX: 15,
    NARROW_PROFESSION_MAX_PX: 18,
  },
  professionLabel: {
    LINE_DELAY: 1.5,
    ALPHA_MULTIPLIER: 0.4,
    LETTER_SPACING: -0.02,
    DELAY: 0.2,
  },
  subtitle: {
    OUTLINE_WIDTH: 0.001,
    LETTER_SPACING: -0.03,
    DELAY: 0.1,
  },
  copy: {
    STAGGER: 0.15,
    DURATION: 0.75,
    LINE_THRESHOLD: 0.1,
  },
  themeSweep: {
    DURATION: 0.62,
    AXIS: [-0.85, -0.53] as [number, number],
    SOFTNESS: 0.19,
    PLANE_Z: -4,
  },
} as const;
